import {
  type AdminFormDefinition,
  type AdminFormSummary,
  type PublicFormDefinition,
} from "@/lib/forms/types";

export const seededLeadForm: PublicFormDefinition = {
  id: 1,
  name: "Lead Intake",
  slug: "lead-intake",
  status: "published",
  successMessage: "送出成功，我們會盡快與您聯繫。",
  theme: {
    brandName: "Classroom MIS",
    logoUrl: "",
    fontHeading: "Manrope",
    fontBody: "Noto Sans TC",
    colorPrimary: "#0f766e",
    colorAccent: "#f59e0b",
    colorSurface: "#f8fafc",
    backgroundStyle: "gradient-soft",
    buttonStyle: "rounded",
  },
  settings: {
    turnstileRequired: true,
    allowMultipleFiles: false,
    maxUploadsPerField: 1,
  },
  fields: [
    {
      id: 11,
      fieldKey: "parent_name",
      label: "家長姓名",
      fieldType: "text",
      placeholder: "請輸入家長姓名",
      helpText: null,
      isRequired: true,
      sortOrder: 1,
      width: "full",
      defaultValue: null,
      validation: { minLength: 2, maxLength: 80 },
      ui: {},
      mapping: { target: "leads.parent_name" },
      options: [],
    },
    {
      id: 12,
      fieldKey: "phone",
      label: "聯絡電話",
      fieldType: "phone",
      placeholder: "例如 0912345678",
      helpText: null,
      isRequired: true,
      sortOrder: 2,
      width: "full",
      defaultValue: null,
      validation: { minLength: 8, maxLength: 20 },
      ui: {},
      mapping: { target: "leads.phone" },
      options: [],
    },
    {
      id: 13,
      fieldKey: "child_name",
      label: "學生姓名",
      fieldType: "text",
      placeholder: "請輸入學生姓名",
      helpText: null,
      isRequired: false,
      sortOrder: 3,
      width: "full",
      defaultValue: null,
      validation: { maxLength: 80 },
      ui: {},
      mapping: { target: "leads.child_name" },
      options: [],
    },
    {
      id: 14,
      fieldKey: "child_grade",
      label: "學生年級",
      fieldType: "select",
      placeholder: null,
      helpText: null,
      isRequired: true,
      sortOrder: 4,
      width: "full",
      defaultValue: null,
      validation: {
        allowedValues: ["K1", "K2", "K3", "G1", "G2", "G3", "G4", "G5", "G6", "other"],
      },
      ui: {},
      mapping: { target: "leads.child_grade" },
      options: [
        { value: "K1", label: "幼兒園小班", sortOrder: 1 },
        { value: "K2", label: "幼兒園中班", sortOrder: 2 },
        { value: "K3", label: "幼兒園大班", sortOrder: 3 },
        { value: "G1", label: "國小一年級", sortOrder: 4 },
        { value: "G2", label: "國小二年級", sortOrder: 5 },
        { value: "G3", label: "國小三年級", sortOrder: 6 },
        { value: "G4", label: "國小四年級", sortOrder: 7 },
        { value: "G5", label: "國小五年級", sortOrder: 8 },
        { value: "G6", label: "國小六年級", sortOrder: 9 },
        { value: "other", label: "其他", sortOrder: 10 },
      ],
    },
    {
      id: 15,
      fieldKey: "source",
      label: "如何得知我們",
      fieldType: "radio",
      placeholder: null,
      helpText: null,
      isRequired: true,
      sortOrder: 5,
      width: "full",
      defaultValue: "website",
      validation: {
        allowedValues: ["walk_in", "referral", "facebook", "line", "website", "flyer", "other"],
      },
      ui: {},
      mapping: { target: "leads.source" },
      options: [
        { value: "walk_in", label: "路過/現場詢問", sortOrder: 1 },
        { value: "referral", label: "親友介紹", sortOrder: 2 },
        { value: "facebook", label: "Facebook", sortOrder: 3 },
        { value: "line", label: "LINE", sortOrder: 4 },
        { value: "website", label: "官方網站", sortOrder: 5 },
        { value: "flyer", label: "傳單", sortOrder: 6 },
        { value: "other", label: "其他", sortOrder: 7 },
      ],
    },
    {
      id: 16,
      fieldKey: "notes",
      label: "備註",
      fieldType: "textarea",
      placeholder: "可填寫學習需求或方便聯絡的時段",
      helpText: null,
      isRequired: false,
      sortOrder: 6,
      width: "full",
      defaultValue: null,
      validation: { maxLength: 1000 },
      ui: { rows: 5 },
      mapping: { target: "leads.notes" },
      options: [],
    },
    {
      id: 17,
      fieldKey: "child_photo",
      label: "學生照片",
      fieldType: "image",
      placeholder: null,
      helpText: "可選填，支援 JPG、PNG、WEBP",
      isRequired: false,
      sortOrder: 7,
      width: "full",
      defaultValue: null,
      validation: {
        maxFileSizeMb: 8,
        allowedMimeTypes: ["image/jpeg", "image/png", "image/webp"],
      },
      ui: {
        accept: "image/jpeg,image/png,image/webp",
      },
      mapping: { target: "leads.extra_json.child_photo" },
      options: [],
    },
  ],
};

export const adminForms: AdminFormSummary[] = [
  {
    id: seededLeadForm.id,
    name: seededLeadForm.name,
    slug: seededLeadForm.slug,
    status: seededLeadForm.status,
  },
];

export const adminFormDetails: AdminFormDefinition[] = [seededLeadForm];
